### ISSUE TITLE
Jurassic requires to be run within an open Fossil repo checkout

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Pesegato/jurassic-fossil#13] opened 2015-03-17 12:47 UTC
```
When Jurassic is launched from within an empty folder, it provides the error 
message "You must run Jurassic from the same folder where your .fossil are."

This is odd behavior as the new version (0.3.2) of Jurassic allows the creation 
of new Fossil repos already. It should probably even *suggest* creating a new 
Fossil repo if it finds that the folder where it launches from does not have 
any open Fossil checkouts.
```

Original issue reported on code.google.com by `jalespr...@gmail.com` on 8 Feb 2011 at 5:32

**Comment by Pesegato** [comment] 2015-03-25 10:34
Working as intended, won't fix.

**Closed as completed by Pesegato** 2015-03-25 10:34 UTC
Labels: Type-Defect, Priority-Medium, auto-migrated
